### ISSUE TITLE
wont open

### ISSUE THREAD

**Issue by rearmstrong69** [r-thomson/Nightfall#4]
it tells me I need to update and contact the developer.

**Comment by r-thomson** [comment]
This is because the builds of Nightfall that I distribute are not signed (signing requires paying to enroll in the Apple developer program).

See [Apple Support: Open a Mac app from an unidentified developer](https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac)
